### ISSUE TITLE
"Other Linker Flags" note on main Docs Page

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/sparkle-project.github.io#12]
> In Build Settings tab set “Other Linker Flags” to -Wl,-rpath,@loader_path/../Frameworks.

I don't ever recall having to do this, and I just created a new Xcode project and didn't need it.

**Comment by jakepetroules** [comment]
If you're running the app from within Xcode, note that Xcode sets DYLD_LIBRARY_PATH and DYLD_FRAMEWORK_PATH to the build products directory, so it will be broken but you won't notice.

So yes, you do need this.

**Comment by zorgiepoo** [comment]
I can launch the app from outside of Xcode too. Feel free to give it a go by creating a new project yourself to verify. It would seem kind of silly for an extra step to be necessary, at least for the common case, if you think about it.

**Comment by jakepetroules** [comment]
Well, creating an application project nowadays sets `LD_RUNPATH_SEARCH_PATHS` to `@executable_path/../Frameworks` (which becomes the `-Wl,-rpath,@executable_path/../Frameworks` argument to the linker). But this wasn't always the case; new projects left the property empty.

It still needs to be set no matter what. I suppose you could update the text to "if it isn't already set" or somesuch (and using the higher level LD_RUNPATH_SEARCH_PATHS build setting is preferred to constructing the linker argument manually).
