### ISSUE TITLE
Document Sparkle Applying Delta Patch is broken in 1.10

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/sparkle-project.github.io#13]
Due to the changes in https://github.com/sparkle-project/Sparkle/commit/d4843c90e8fb1ca38833985484e8c1e39d4b7b0a , applying delta patches was broken and could cause a crash. This only affects version 1.10 (I think) and also note that the issue was not within BinaryDelta tool itself, but in Sparkle's updater.

Or for simplicity sake, I suppose we could just say don't use binary deltas prior to version 1.11.

**Comment by zorgiepoo** [comment]
https://github.com/sparkle-project/Sparkle/issues/536 explains the fix.

**Comment by jakepetroules** [comment]
Where/how do you suggest we document this?

**Comment by zorgiepoo** [comment]
On the delta updates page.

Below

> Version 2 patches created by BinaryDelta are not backwards compatible with Sparkle 1.9 or earlier. Pass `--version=1` when creating patches only if you want old versions to apply them.

We could put:

> We don't recommend creating patches from an application that uses Sparkle 1.10; this is because that version can cause a potential crash when applying a delta update.

Or this can be worded differently or moved somewhere else on the page, like the top. Feel free to suggest something.

**Comment by jakepetroules** [comment]
I think what you suggested makes sense. Feel free to open a PR.
