### ISSUE TITLE
Cannot bind to NSTimeInterval

### ISSUE THREAD

**Issue by mdfw** [sparkle-project/sparkle-project.github.io#15]
`documentation/preferences-ui/` states _"choose Updater from the popup, and set the Model Key Path to updateCheckInterval."_ However, if you try this, you'll get a friendly error on the bindings panel and then a nice crash if you ignore it. The `selectedTag` binding expects to be bound to a `NSNumber` but `updateCheckInterval` is `NSTimeInterval`. 

Options:
1. Tell me something I don't know about convincing this to work (and update the docs). This is my hopeful answer.
2. Remove this from the docs.
3. Add something to `SUUpdater` to is bindings capable (I can open a separate bug against the main project if you wish).

I've worked around this for now in code, but wanted to point it out.

**Comment by jakepetroules** [comment]
This seems to work perfectly fine. Are you sure you didn't make a mistake?
