### ISSUE TITLE
App Transport Security

### ISSUE THREAD

**Issue by sstanleyau** [sparkle-project/sparkle-project.github.io#19]
Apps that specify HTTP addresses for appcasts (and are linked to the 10.11 SDK?) can't update under 10.11 unless they add an exception for the domain to their Info.plist files ("App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure."). That seems like an issue that should be mentioned fairly prominently in the docs.

**Comment by zorgiepoo** [comment]
Yes it requires linking to the 10.11 SDK, and it's not just the app cast. Pretty much any type of http request in the app. Still it would not hurt mentioning it in the docs.

**Comment by sstanleyau** [comment]
For a lot of apps I can imagine Sparkle is the only thing making an HTTP request, so it could easily be overlooked. At which time getting updates to fix the problem becomes problematical...

**Comment by pornel** [comment]
Updated too http://sparkle-project.org/documentation/publishing/#publishing-an-update
