### ISSUE TITLE
Add documentation for de-emphasizing past releases

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/sparkle-project.github.io#194]
Add documentation for de-emphasizing past releases as part of https://github.com/sparkle-project/Sparkle/pull/2373

I think this should be on https://sparkle-project.org/documentation/publishing/ page after the "Full release notes" section.

Section title could be `De-emaphasize past releases` or something similar. Not sure if it should favor `opacity: 0.5` or `display: none` as an example, or maybe choose the more preferable one for demonstration, and comment that the other is possible.

It maybe should mention this feature requires Sparkle 2.5 (beta) but it is also backwards compatible with older releases anyway (no harmful effect).

**Comment by Cykelero** [comment]
I'll take a stab at this! Do you have any rough deadline in mind?

Making the code example as readily copy-and-pasteable as possible feels like a good goal (for saving people time, and encouraging a standardized implementation), so I'm thinking of using `display: none` in the sample, and then mentioning using `opacity` as an alternate style.
