### ISSUE TITLE
Use the GitHub JSON API to automatically determine the latest release

### ISSUE THREAD

**Issue by jakepetroules** [sparkle-project/sparkle-project.github.io#2]
Use: `https://api.github.com/repos/sparkle-project/Sparkle/releases`

It should be the first release that isn't a draft or pre-release.

**Comment by grahammiln** [comment]
Pull request #4 offers an approach that avoids scripting.

Linking to the [latest release](https://github.com/sparkle-project/Sparkle/releases/latest) in GitHub is probably not the best solution. However, this approach ensures visitors always get the latest version. It also reduces the burden on administrators to update the web site.
