### ISSUE TITLE
Make HTTPS the default

### ISSUE THREAD

**Issue by reedloden** [sparkle-project/sparkle-project.github.io#26]
Thanks to https://github.com/sparkle-project/Sparkle/issues/727, https://sparkle-project.org now works. Would be good to make https:// the default by:

1. 301 redirecting http:// to https://;
2. adding appropriate HSTS header with long max-age;
3. adding sparkle-project.org to HSTS preload list at https://hstspreload.appspot.com

**Comment by jakepetroules** [comment]
You posted while CloudFront settings were updating. :)

**Comment by reedloden** [comment]
@jakepetroules Not sure if CloudFront allows you to set the HSTS header, but if not, you should submit a custom request to get it manually added to the HSTS preload list. :)
