### ISSUE TITLE
Apple system font in Safari 9

### ISSUE THREAD

**Issue by Eitot** [sparkle-project/sparkle-project.github.io#32]
Apple added this new font-family value `-apple-system` to Safari 9 and iOS 9, which renders the text in the system typeface. This is a great way to get San Francisco. I think it looks a bit better alongside the screenshot on the front page and is easier to read on non-Retina devices (Helvetica Neue looks pixel-y when very thin). On Yosemite (with Safari 9) this value defaults to Helvetica Neue, on Mavericks to Lucida Grande and in every other browser it is simply skipped.

https://webkit.org/blog/3709/using-the-system-font-in-web-content/

The only real downside is that Mavericks will be saddled with Lucida Grande. What do you think?

**Comment by pornel** [comment]
We currently use `-apple-system-font`, which seems to have the same effect, but is more backwards compatible.

**Comment by Eitot** [comment]
Where are you using it? I don’t see it mentioned anywhere.

**Comment by pornel** [comment]
Oh, I thought you've meant Release Notes window in Sparkle.
