### ISSUE TITLE
Remove Cocoapod Alternative Instructions

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/sparkle-project.github.io#35]
Can we remove the alternative instructions for Cocoapods or clearly mention that those instructions only could possibly apply to a really old version of Xcode at this point? Xcode can code sign Sparkle when copying the framework just fine without a run script.

See [this issue](https://github.com/sparkle-project/Sparkle/issues/709) for more detail and how it can even cause trouble.

**Comment by jakepetroules** [comment]
Xcode 6 and above have code sign on copy, I think. It should be rewritten.
