### ISSUE TITLE
Support for Xcode 8

### ISSUE THREAD

**Issue by tonkaskippers** [sparkle-project/sparkle-project.github.io#44]
Can you update sparkle support for Xcode 8?  The tutorial is obsolete.

**Comment by pornel** [comment]
What is not right with it?

**Comment by tonkaskippers** [comment]
I tried to do this step, and think it has changed.

Make sure the framework is copied into your app bundle:
Click on your project in the Project Navigator.
Click your target in the project editor.
Click on the Build Phases tab.
Choose Editor › Add Build Phase › Add Copy Files Build Phase.
Click the disclosure triangle next to the new build phase.
Choose Frameworks from the Destination list.
Drag Sparkle.framework from the Project Navigator left sidebar to the list in the new Copy Files phase.
In Build Settings tab set “Runpath Search Paths” to @loader_path/../Frameworks (for non-Xcode projects add the flags -Wl,-rpath,@loader_path/../Frameworks).
If you have your own process for copying/packaging your app make sure it preserves symlinks!

**Comment by pornel** [comment]
It's still accurate as of Xcode 8.3

![screen shot 2017-04-10 at 16 51 56](https://cloud.githubusercontent.com/assets/72159/24870374/01b121bc-1e0e-11e7-9609-397e656506af.png)

**Comment by tonkaskippers** [comment]
Oh, I understand now.  I learn visually, so screenshots like that help.  Would you be willing to add some to the tutorial?

**Comment by zorgiepoo** [comment]
The steps have changed, might be easier to grok now. If not, contributions welcome.
