### ISSUE TITLE
Contrubite Designing Sparkle Website 🎨

### ISSUE THREAD

**Issue by dbrownjave** [sparkle-project/sparkle-project.github.io#47]
Hello, 
I'm a Front-End Developer and UI/UX designer. I want to contribute to the website. Therefore, how can ask or have permission to make Sparkle website more beautiful?

Note: I don't want to change the layout. I just want to improve UI/UX

**Comment by kornelski** [comment]
Yes, definitely. Design/UX contributions are very welcome!

**Comment by ZEUSOFCS** [comment]
Awesome. Do I need permission to contribute?

**Comment by kornelski** [comment]
You do not need a permission to get started. To make changes live, you need someone on the project to accept and merge the changes.

You can take a copy of the project (clone the site), apply any changes you like, and then make a pull request.

**Comment by ZEUSOFCS** [comment]
Perfect! Thanks for the fast response 👏🏽

**Comment by kornelski** [comment]
We use static site generator called Jekyll.

1. [Install Jekyll](https://jekyllrb.com/docs/installation/#macOS).

2. Run in terminal:

   ```sh
   jekyll serve
   ```

3. Open [http://127.0.0.1:4000/](http://127.0.0.1:4000/) in your browser.

**Comment by ZEUSOFCS** [comment]
Awesome! I got it to work 😀
