### ISSUE TITLE
Incorrect text on Preferences UI bindings documentation page

### ISSUE THREAD

**Issue by lostminds** [sparkle-project/sparkle-project.github.io#53]
Hello, on the documentation page for Preferences UI bindings
https://sparkle-project.org/documentation/preferences-ui/
there are some copy-paste mistakes I think. The last two steps in binding the Update check interval settings still refers to the checkbox and key for automaticallyChecksForUpdates, instead of the popup menu and updateCheckInterval key. 

Also, perhaps a list of the available Model Key Paths and their types could be a nice addition here? Their names don't seem to be the exact same as the .plist keys the current page link refers to on https://sparkle-project.org/documentation/customization/#infoplist-settings

**Comment by zorgiepoo** [comment]
I don't think the documentation is wrong after taking a second look. The model key paths are based on the properties from the updater class.
