### ISSUE TITLE
Website footer: update copyright year

### ISSUE THREAD

**Issue by case** [sparkle-project/sparkle-project.github.io#58]
It looks like this is being generated on build time here:

https://github.com/sparkle-project/sparkle-project.github.io/blob/master/_layouts/default.html#L87

…so a simple rebuild + deploy should bump 2019 -> 2020.

**Comment by zorgiepoo** [comment]
This is technically wrong. Copyright year is supposed to be first year, not latest.

**Comment by zorgiepoo** [comment]
Well it includes initial year + has been updated recently now.
