### ISSUE TITLE
"Modern" - really?

### ISSUE THREAD

**Issue by lhaeger** [sparkle-project/sparkle-project.github.io#60]
https://sparkle-project.org/ claims:

```
Modern

Sparkle is kept up to date with the latest Apple technologies: it uses ARC and Auto Layout and supports macOS versions 10.7 through 10.11 and Xcode 5.0 through 7.0.
```
Those macOS and Xcode versions are far from being modern. My machine is currently at

```
macOS 10.15.5 19F101
Xcode 11.5 11E608c
```
Please update the website to reflect reality. Maybe just say "macOS 10.7 and Xcode 5.0 or newer"...

**Comment by kornelski** [comment]
Haha. That didn't age well. Can you make a PR updating this paragraph?

**Comment by lhaeger** [comment]
No, I'll leave that to someone actually knowledgeable about the matter. :-)
